tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 1880
    onOpen: open-browser
