################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    container_name: node-red
    build:
      context: .
      dockerfile: ./nodered2.Dockerfile
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    networks:
      - tibotnet
    volumes:
      - ./node-red-data2:/data 

  
volumes:

  node-red-data2:

networks:
  tibotnet: