version: "3.7"

services:
  node-red:
    container_name: node-red
    build:
      context: .
      dockerfile: ./nodered2.Dockerfile
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    networks:
      - tibotnet
    depends_on:
      - redis
    volumes:
      - ./node-red-data2:/data 

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass YzRAdGgkFg
    ports:
     - "6379:6379"
    environment:
         - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis-data:/data
      #- ./redisconf:/usr/local/etc/redis
    restart: always
    networks:
      - tibotnet

  priceserver:
    container_name: priceserver
    build:
      context: ./priceserver
      dockerfile: ./Dockerfile.dev
    volumes:
      - './priceserver/:/usr/src/app'
    restart: always
    depends_on:
      - redis
    networks:
      - tibotnet

volumes:
  redis-data:
  node-red-data2:

networks:
  tibotnet: